spring:
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
  datasource:
    url: jdbc:postgresql://${DATASOURCE_URL}/${DATASOURCE_DATABASE}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtpout.secureserver.net
            enable: false
            protocols: TLSv1.2
          from: ${MAIL_FROM}
# Jwt secret
jwt:
  secret: ${JWT_SECRET}

app:
  domain: localhost # Default to localhost for dev, override with thewealthweb.in for prod


MAIL_FROM: info@thewealthweb.in
MAIL_HOST: smtpout.secureserver.net
MAIL_PORT: 587
MAIL_USERNAME: info@thewealthweb.in
MAIL_PASSWORD: Jx/*UpS4x&VvYL.