spring:
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
  datasource:
    url: jdbc:postgresql://${DATASOURCE_URL}/${DATASOURCE_DATABASE}?options=-c%20timezone=Asia/Kolkata
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:none}
    password: ${MAIL_PASSWORD:none}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtpout.secureserver.net
            enable: false
            protocols: TLSv1.2
          from: ${MAIL_FROM:noreply@localhost}
# App settings for Tenant resolution
app:
  domain: ${APP_DOMAIN:localhost}

# Jwt secret
jwt:
  secret: ${JWT_SECRET:dGhpcy1pcy1hLXZlcnktc2VjcmV0LWtleS1mb3Itand0LXRoYXQtc2hvdWxkLWJlLWNoYW5nZWQtaW4tcHJvZHVjdGlvbg==}


aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
    region: ${AWS_S3_REGION}
  access:
    key: ${AWS_ACCESS_KEY}
  secret:
    key: ${AWS_SECRET_KEY}